# This file was generated by GoReleaser. DO NOT EDIT.
class Esk < Formula
  desc "A simple library for building a project following the event sourcing pattern."
  homepage "https://github.com/wcatron/esk"
  version "0.2.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/wcatron/esk/releases/download/v0.2.5/esk_0.2.5_Darwin_x86_64.tar.gz"
    sha256 "1a836e851eb5f96ff44e48e483be7840eb31f01f3030f9dd3dce2ef6a5b3e20f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/wcatron/esk/releases/download/v0.2.5/esk_0.2.5_Linux_x86_64.tar.gz"
    sha256 "1de55d534e731e32dca47c29a45c8f3a212982ad5e330d20ef6a5a8d079d8fd5"
  end

  def install
    bin.install "esk"
  end
end
